"""Added probabity_awayscore column to Fixture model

Revision ID: 075b4a4a41e2
Revises: 1b3411a33d83
Create Date: 2025-02-26 04:59:21.465078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075b4a4a41e2'
down_revision = '1b3411a33d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twoteams_score', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('probabity_homescore', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('probabity_awayscore', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('probabity_awayscore')
        batch_op.drop_column('probabity_homescore')
        batch_op.drop_column('twoteams_score')

    # ### end Alembic commands ###
