"""Added email column to Fixture model

Revision ID: 1b3411a33d83
Revises: 3067fd33428a
Create Date: 2025-02-26 04:43:05.745434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b3411a33d83'
down_revision = '3067fd33428a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_name', sa.String(length=240), nullable=True))

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_home', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goal_away', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('probabity', sa.Double(), nullable=True))
        batch_op.alter_column('result_status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'fixtures', ['fixture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('result_status',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('probabity')
        batch_op.drop_column('goal_away')
        batch_op.drop_column('goal_home')

    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('league_name')

    # ### end Alembic commands ###
