"""Added email column to Fixture model

Revision ID: 1bec7f0a7b58
Revises: 
Create Date: 2025-02-25 11:45:46.968179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bec7f0a7b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(length=240), nullable=True),
    sa.Column('timezone', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.Numeric(), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.Column('st_long', sa.String(length=32), nullable=True),
    sa.Column('st_short', sa.String(length=32), nullable=True),
    sa.Column('st_elapsed', sa.String(length=32), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('league_season', sa.Integer(), nullable=True),
    sa.Column('league_round', sa.String(length=240), nullable=True),
    sa.Column('team_home_id', sa.Integer(), nullable=True),
    sa.Column('team_away_id', sa.Integer(), nullable=True),
    sa.Column('team_away_winner', sa.Boolean(), nullable=True),
    sa.Column('team_home_winner', sa.Boolean(), nullable=True),
    sa.Column('team_home_name', sa.String(length=240), nullable=True),
    sa.Column('team_away_name', sa.String(length=240), nullable=True),
    sa.Column('goal_home', sa.Integer(), nullable=True),
    sa.Column('goal_away', sa.Integer(), nullable=True),
    sa.Column('score_ht_home', sa.Integer(), nullable=True),
    sa.Column('score_ht_away', sa.Integer(), nullable=True),
    sa.Column('score_ft_home', sa.Integer(), nullable=True),
    sa.Column('score_ft_away', sa.Integer(), nullable=True),
    sa.Column('score_ext_home', sa.Integer(), nullable=True),
    sa.Column('score_ext_away', sa.Integer(), nullable=True),
    sa.Column('score_pt_home', sa.Integer(), nullable=True),
    sa.Column('score_pt_away', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_exact', sa.JSON(), nullable=True),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
