"""Added ficture to Fixture model

Revision ID: 1fc794edfbab
Revises: 075b4a4a41e2
Create Date: 2025-02-26 08:38:27.371601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc794edfbab'
down_revision = '075b4a4a41e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mitemps_score', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('mitemps_score')

    # ### end Alembic commands ###
