"""Added email column to Fixture model

Revision ID: 3067fd33428a
Revises: 1bec7f0a7b58
Create Date: 2025-02-25 14:35:39.716846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3067fd33428a'
down_revision = '1bec7f0a7b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_home_logo', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('team_away_logo', sa.String(length=240), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('team_away_logo')
        batch_op.drop_column('team_home_logo')

    # ### end Alembic commands ###
