"""Added ficture to Fixture model

Revision ID: 46b7cdc1dd1e
Revises: 1fc794edfbab
Create Date: 2025-02-26 14:06:02.469602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b7cdc1dd1e'
down_revision = '1fc794edfbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
