"""Added ficture to Fixture model

Revision ID: 738d67f2cfc8
Revises: 46b7cdc1dd1e
Create Date: 2025-02-26 14:49:00.291942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '738d67f2cfc8'
down_revision = '46b7cdc1dd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probabity_home_win', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('probabity_away_win', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('probabity_draw', sa.Double(), nullable=True))
        batch_op.drop_column('probabity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probabity', mysql.DOUBLE(asdecimal=True), nullable=True))
        batch_op.drop_column('probabity_draw')
        batch_op.drop_column('probabity_away_win')
        batch_op.drop_column('probabity_home_win')

    # ### end Alembic commands ###
